apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-stats
  labels:
   app: python-stats 
spec:
 replicas: 10
 selector:
  matchLabels:
   app: python-stats
 template:
  metadata:
   labels:
    app: python-stats    
  spec:
    hostNetwork: true
    containers:
    - name: test-server
      image: gcr.io/edhofmann-sandbox/prom-python-app:0.3
      ports:
        - name: python-metrics
          containerPort: 8000
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 5     
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 150m             