global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Python-Example'
    metrics_path: /
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['ENTERIPHERE:8000']
