apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
   app: prometheus 
spec:
 replicas: 1
 selector:
  matchLabels:
   app: prometheus
 template:
  metadata:
   labels:
    app: prometheus    
  spec:
    hostNetwork: true
  containers:  
    - name: prometheus
      image: prom/prometheus:latest
      args:
        - "-config.file=/etc/prometheus/conf/prometheus.yml"
        # Metrics are stored in an emptyDIR volume
        # Which Exists as long as the pod is running
        # The data is safe accross container crashes.
        - "-storage.local.path=/prometheus/"
      ports:
        - name: prom-port
          containerPort: 9090
      volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/conf/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      readinessProbe:
        httpGet:
          path: /
          port: 9090
        initialDelaySeconds: 10
        timeoutSeconds: 10
      resources:
        requests:
          memory: 300Mi
          cpu: 100m
        limits: 
          memory: 300Mi
          cpu: 100m         
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {} # containers in the Pod can all read and write the same files here.      